// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/app/AppProvider.vue')['default']
    DialogContent: typeof import('./../components/app/DialogContent.vue')['default']
    IFa6SolidTemperatureHalf: typeof import('~icons/fa6-solid/temperature-half')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiKeyboardArrowDown: typeof import('~icons/mdi/keyboard-arrow-down')['default']
    IMdiKeyboardArrowUp: typeof import('~icons/mdi/keyboard-arrow-up')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiMenuClose: typeof import('~icons/mdi/menu-close')['default']
    IMdiTemperatureCelsius: typeof import('~icons/mdi/temperature-celsius')['default']
    LoadingBarContent: typeof import('./../components/app/LoadingBarContent.vue')['default']
    MsgContent: typeof import('./../components/app/MsgContent.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NotificationContent: typeof import('./../components/app/NotificationContent.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NTable: typeof import('naive-ui')['NTable']
    PageCard: typeof import('./../components/pages/PageCard.vue')['default']
    PageSingle: typeof import('./../components/pages/PageSingle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SugonMap: typeof import('./../components/SugonMap.vue')['default']
    SugonNumber: typeof import('./../components/SugonNumber.vue')['default']
    SugonVideo: typeof import('./../components/SugonVideo.vue')['default']
  }
}
